version: '2'
services:
  app:
    build: .
    tty: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - .:/work/docker-ruby-test:cached
      - vendor:/work/docker-ruby-test/vendor
      - tmp:/work/docker-ruby-test/tmp
      - log:/work/docker-ruby-test/log
      - .git:/work/docker-ruby-test/.git
    links:
        - mysql

  mysql:
    image: mysql:5.6.23
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    
volumes:
  vendor:
  tmp:
  log:
  .git:
  mysql-data:
    driver: local

